
# Environment for the metaservice using Flask.

# Pull base image.
FROM ubuntu:18.04

# Add user
RUN groupadd -g 9999 rds && \
    useradd -r -u 9999 -g rds -m -d /home/rds rds

# Install packages.
RUN \
    apt-get update && \
    apt-get install -y \
        git \
        python3-flask \
        python3-requests \
        vim \
        wget && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/*

# Switch user and working directory.
USER rds
WORKDIR /home/rds
COPY --chown=rds:rds [".bashrc", "/home/rds/"]

# Define default command.
CMD ["bash"]

COPY --chown=rds:rds [".", "/home/rds/rds-meta/"]

ENTRYPOINT /home/rds/rds-meta/start.sh && /bin/bash
